# --------------------------------------------------
# Embedding model
# --------------------------------------------------

model_name: sentence-transformers/all-MiniLM-L6-v2

# --------------------------------------------------
# Device
# --------------------------------------------------

device: cuda

# --------------------------------------------------
# Embedding generation
# --------------------------------------------------

batch_size: 128

normalize_embeddings: true

show_progress_bar: true

# --------------------------------------------------
# Saving
# --------------------------------------------------

save_embeddings: true

embeddings_path: indexes/embeddings